mixed-port: 7890
redir-port: 7891
allow-lan: false
mode: Rule
log-level: info
ipv6: false
hosts:
  local.lan: "127.0.0.1"
experimental:
  ignore-resolve-fail: false # 忽略 DNS 解析失败，默认值为 true
    # 本地 SOCKS5 / HTTP(S) 服务认证
authentication:
  - "user1:pass1"
  - "user2:pass2"
clash-for-android:
  append-system-dns: true 
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:1053
  enhanced-mode: redir-host
  default-nameserver:
    - 156.154.70.5
    - 156.154.71.5
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - 156.154.70.5
    - 156.154.71.5    
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 156.154.70.5
    - 156.154.71.5
    - 223.5.5.5
    - 8.8.8.8
  fallback-filter:
    geoip: false
    ipcidr:
      - 127.0.0.0/8
      - 0.0.0.0/32
proxies: ~
proxy-groups: ~
rules: ~ 
