mixed-port: 7890
redir-port: 7891
allow-lan: false
mode: Rule
log-level: info
ipv6: true
hosts:
  local.lan: "127.0.0.1"
# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
clash-for-android:
  append-system-dns: true 
dns:
  enable: true
  ipv6: true
  listen: 127.0.0.1:1053
  enhanced-mode: redir-host
  default-nameserver:
    - 1.2.4.8
    - 156.154.70.5
    - 156.154.71.5
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - 1.2.4.8
    - 156.154.70.5
    - 156.154.71.5    
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - 1.2.4.8
    - 156.154.70.5
    - 156.154.71.5    
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
    - 1.1.1.1
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 127.0.0.0/8
      - 0.0.0.0/32
proxies: ~
proxy-groups: ~
rules: ~ 
